idf_component_register(
  SRCS
    "main.c"
    "config/app_config.c"
    "display/bmp_decoder.c"
    "display/display_driver.c"
    "hardware/buttons.c"
    "hardware/buzzer.c"
    "hardware/sensors.c"
    "network/mqtt_app.c"
    "network/server_api.c"
    "network/wifi_portal.c"
  INCLUDE_DIRS
    "config"
    "display"
    "hardware"
    "network"
  REQUIRES
    driver
    esp_adc
    esp_event
    esp_driver_ledc
    esp_hw_support
    esp_http_client
    esp_http_server
    esp_netif
    esp_app_format
    app_update
    esp_timer
    esp_wifi
    freertos
    heap
    cjson
    log
    lwip
    mbedtls
    mqtt
    nvs_flash
    esp_epaper
)
